### ISSUE TITLE
Update main server

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#192]
Our main tile server will be updated to Ubuntu 18.04 LTS by installing a new operating system and deleting the server content. :boom:

Following tasks need to be performed:
- [X] prepare backup tile server
- [x] backup
  - [X] www
  - [X] tiles 1-14
  - [x] contours and hillshade files
- [x] switch domains to backup tile server
- [x] install Ubuntu 18.04
- [x] tirex, mod_tile
- [x] postgresql, mapnik
- [x] munin, awstats
- [x] populate database
  - [x] contours
  - [x] planet file
  - [x] preprocessing
- [x] start tile server
- [x] switch domains to main server again

**Comment by tomislav** [comment]
How long will this update take?

**Comment by der-stefan** [comment]
It could take longer, since I encountered several unexpected problems (like systemd) when installing Ubuntu 18.04. Due to lack of free time in the next weeks it could get October or even November. That's the drawback of non-commercial two-men hobby projects... :grimacing:

**Comment by der-stefan** [comment]
By the way: The new Ubuntu 18.04 uses netplan instead of ``/etc/network/interfaces``. Netplan and the yaml format SUCK!!! I only have 1-2 hours of free time every couple of days and still did not get the bond interface to work in the third attempt! I am giving up again for today! :shit: :rage: :bomb: :boom:

**Comment by mobidev111** [comment]
as an idea/suggestion to speed this up - and a possibility on how the community could assist you:

# automate server setup using docker / docker-compose

putting the application into containers with docker allows for codifying the infrastructure configuration - and thus sharing it.

## advantages: 
- moving to a new server in minutes - by having a complete automated setup
- save time on configuration by re-using other map server docker configurations
- the community can help in setting up your opentopomap server

## examples / architecture

Some posts that go in this direction:

* Generating Maps With Mapnik and Docker (shows complete configuration & howto)
  - "a configuration to launch your own retina ready map renderer"
  - detailed howto: https://dzone.com/articles/generating-maps-with-mapnik-and-docker
  - sources: https://github.com/dooman87/melbourne-map
  - docker file for renderer component (mapnik/gopnik): https://github.com/dooman87/melbourne-map/blob/master/renderer/Dockerfile
  - docker-compose file bringing the components together
https://github.com/dooman87/melbourne-map/blob/master/docker-compose.yml

* some other map server docker configurations
https://github.com/zavpyj/osm-tiles-docker
https://github.com/geo-data/openstreetmap-tiles-docker
https://www.reddit.com/r/openstreetmap/comments/8i07jl/i_created_an_uptodate_docker_file_to_run_your_own/
https://github.com/Overv/openstreetmap-tile-server
https://store.docker.com/images/openmaptiles-openstreetmap-maps

* Detailed documented steps to setup OpenStreetMap Tile Server on Ubuntu
  - not yet as docker script but an already documented setup process
https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/

## tasks

The task list could be extended as follows:
- [ ] create OpenTopoMap-docker repo
- [ ] add dockerfile for each component
- [ ] add docker-compose file for whole map server

**Comment by der-stefan** [comment]
@mobidev111 This is a very good idea! Docker seems to be the application I was looking for. I'll start that soon™...

**Comment by der-stefan** [comment]
Setting up a tile server from a fresh Ubuntu 18.04 causes pain! It seems to me that the setup is more difficult than before.
